### ISSUE TITLE
should init.sql create extension citext;?

### ISSUE THREAD

**Issue by seiyria** [RealmOfAesir/world#1]
http://stackoverflow.com/questions/15981197/postgresql-error-type-citext-does-not-exist

I ran into this initially.

**Comment by Oipo** [comment]
According to [postgres documentation](https://www.postgresql.org/docs/9.1/static/sql-createextension.html) you need superuser or database owner privileges. Testing it personally, for citext you need superuser privileges. For security purposes, the aesir database should be owned by a separate user that does not have superuser privileges, lest your entire postgresql instance be fucked if RoA is ever compromised.

As such, the creation of the citext extension will not be placed in any init or seed sql scripts.
